/* Generated by 'unplugin-unocss-config' */
import type { Theme } from '@unocss/preset-mini'

declare const __UNO__: Pick<ReturnType<typeof import('@unocss/core').createGenerator<Theme>>, 'config' | 'userConfig' | 'version' | 'blocked'>

declare const __UNO_CONFIG__: import('@unocss/core').UserConfig<Theme>

declare const __UNO_THEME__: Theme

interface ImportMetaEnv {
  readonly __UNO__: Pick<ReturnType<typeof import('@unocss/core').createGenerator<Theme>>, 'config' | 'userConfig' | 'version' | 'blocked'>
  readonly __UNO_CONFIG__: import('@unocss/core').UserConfig<Theme>
  readonly __UNO_THEME__: Theme
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
