interface ImportMetaEnv {
  /* Generated by 'unplugin-unocss-config' */
  readonly __UNO__: Pick<ReturnType<typeof import('unocss').createGenerator>, 'config' | 'userConfig' | 'version'>
  readonly __UNO_CONFIG__: import('unocss').UserConfig
  readonly __UNO_THEME__: import('unocss').UserConfig['theme']
}

interface ImportMeta {
  readonly bbb: ImportMetaEnv
  readonly env: ImportMetaEnv
  readonly aaa: ImportMetaEnv
}
